# Dependencies
highlighter:      rouge

# Config
gems: [jekyll-gist,jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            "The great unravelling" 
tagline:          "China's economic and financial challenges"
description:      "China's economic and financial challenges"
url:              http://digitalframeworks.github.io
baseurl:          /

author:
  name:           'Harvard Zhang'
  url:            https://twitter.com/harvardzhang

paginate:         15

exclude: [node_modules]

sass:
  sass_dir: _sass
  style: compressed

# Custom vars
navlinks:
- url: https://nwudigitalframeworks.slack.com/messages/general/
  title: Slack
- url: mailto:davideads@gmail.com
  title: Email
